apiVersion: v1
kind: Pod
metadata:
  labels:
    label: jenkins-job
spec:
  containers:
  - name: jenkins-job
    image: ${image}
    command: ["sleep"]
    args: ["100000"]
    tty: true
    imagePullPolicy: "Always"
    volumeMounts:
#    - mountPath: "/root/.ssh"
#      name: "volume-0"
#      readOnly: false
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volum"
      readOnly: false
    workingDir: "/home/jenkins/agent"
  - name: jnlp
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volum"
      readOnly: false
  volumes:
#  - name: "volume-0"
#    secret:
#      defaultMode: 384
#      secretName: "jenkins-ssh-key"
  - emptyDir:
      medium: ""
    name: "workspace-volum"
  imagePullSecrets:
  - name: "harbor.qianfan123.com"
  - name: "harbor-admin"
#  nodeSelector:
#    app: "jenkins"
  serviceAccount: "jenkins"
  restartPolicy: "Never"
