apiVersion: v1
kind: Pod
metadata:
  labels:
    label: jenkins-job
spec:
  containers:
  - name: jenkins-job
    image: ${image}
    command: ["sleep"]
    args: ["100000"]
    tty: true
    imagePullPolicy: "Always"
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volum"
      readOnly: false
    workingDir: "/home/jenkins/agent"
  - name: jnlp
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volum"
      readOnly: false
  volumes:
  - emptyDir:
      medium: ""
    name: "workspace-volum"
  imagePullSecrets:
  - name: "harbor.qianfan123.com"
  - name: "harbor-admin"
  - name: "harborka.qianfan123.com"
  serviceAccount: "jenkins"
  restartPolicy: "Never"
